// Canonical content routes (the 34 page_content keys). Inline links may only
// point at these; anything else renders as plain text.
export const ACTIVE_PATHS = [
  "/",
  "/power-of-attorney",
  "/power-of-attorney/general",
  "/power-of-attorney/real-estate",
  "/power-of-attorney/vehicle",
  "/power-of-attorney/bank",
  "/power-of-attorney/special",
  "/power-of-attorney/court",
  "/power-of-attorney/child-travel",
  "/power-of-attorney/inheritance",
  "/power-of-attorney/company-formation",
  "/power-of-attorney/company-management",
  "/power-of-attorney/property-gifting",
  "/power-of-attorney/mohre",
  "/power-of-attorney/real-estate/sale",
  "/power-of-attorney/real-estate/purchase",
  "/power-of-attorney/real-estate/management",
  "/power-of-attorney/real-estate/handover",
  "/power-of-attorney/vehicle/sale",
  "/power-of-attorney/vehicle/export",
  "/power-of-attorney/vehicle/management",
  "/legal-notice/eviction",
  "/legal-notice",
  "/legal-notice/poa-cancellation",
  "/e-notary",
  "/mobile-notary",
  "/last-will-testament-dubai",
  "/poa-cancellation",
  "/emergency-notary",
  "/rdc-support",
  "/document-rejection",
  "/what-is-tableegh",
  "/why-poa-rejected-dubai",
  "/faq",
  "/about",
  "/contact"
] as const
